### ISSUE TITLE
Kelvin?

### ISSUE THREAD

**Issue by strelniece** [mwittig/node-red-contrib-milight#1]
Can't set kelvin on RGBWWCW lamps. Is it possible to fix that?

**Comment by mwittig** [comment]
Hi. 

Thanks for using node-red-contrib-milight. I'll add support for setting the white temperature asap. Note, however, it is not possible to provide a kelvin value directly, but a relative value (ranging from 0 .. 100) can be set.

EDIT:  0 is roughly maps to 2700 K and 100 is 6500 K

**Comment by mwittig** [comment]
released
