### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by mAPBhlJ** [mwittig/node-red-contrib-milight#2]
I've set up an iBox 2 (connected to the network and assigned my lights to the groups).
Controlling from the app works fine as well as controlling from another remote.
I'm running Node-Red on Windows 10, both being on the same network.

I've loaded up the example flow and tried both with the original config (broadcast), also changed it to the correct bridge type and tried to configure to connect directly to the IP of the ibox. 
But somehow my lights will just not respond to any of the commands.

Are there any known issues with running on windows or how would I be able to debug this problem?

EDIT:

I've digged a little and found node-milight-promise and running the discover-bridges-v6.js example actually returns the mac/name/ip/type of my bridge. But the other examples only seem to return "Invocation of asynchronous Milight commands done", but nothing happens.

**Comment by mwittig** [comment]
Sorry for delayed reply. Did you solve this?

I am using the plugin on Windows and it is working fine.

**Comment by mwittig** [comment]
No response.
