### ISSUE TITLE
8zone control

### ISSUE THREAD

**Issue by rspaargaren** [mwittig/node-red-contrib-milight#3]
Would it be possible to add the 8zone control to the option list. As the commands are already available in the node-milight-promise...?

**Comment by mwittig** [comment]
Sure, will do

**Comment by agoralive** [comment]
Hi

Did you get a chance to add this yet, or could you perhaps do this?

**Comment by mwittig** [comment]
Sorry for the delay. 

I have implemented experimental support for this which is about to be released. Please give it a try and report back your findings. Thanks

**Comment by mwittig** [comment]
published node-red-contrib-milight-2@1.0.8

**Comment by mwittig** [comment]
No feedback from requestor. Closing this now.
