### ISSUE TITLE
Not an issue but rather a question

### ISSUE THREAD

**Issue by mikecay** [mwittig/node-red-contrib-milight#5]
Does the milight support the milight recessed light like this

https://www.ebay.ca/itm/milight-RGBW-RGB-Dimmable-WIFI-Recessed-LED-Ceiling-Panel-bulb-Light-Downlight/292480005195?hash=item44192ab44b%3Am%3Am_F9aKg8m7tFo3Hw81vmi_A&var=591326073606

Thank you,

Mike

**Comment by mwittig** [comment]
I have no idea to be honest. I'd say it should work, but I am not aware of anyone who tried these bulbs.
