### ISSUE TITLE
using esp8266 hub

### ISSUE THREAD

**Issue by orbyog** [mwittig/node-red-contrib-milight#6]
if i try to set the port number of the ip (ex123.123.123.123:4321) it returns error "getaddrinfo ENOTFOUND" is there a way i can set what port i want to use?

**Comment by mwittig** [comment]
This feature is currently not supported. The address field only takes a plain IP address

**Comment by orbyog** [comment]
Thank you for your reply.
The esp hub (https://github.com/sidoh/esp8266_milight_hub) emulates the v5,v6 hub but allows you to create multiple instances by assigning different port numbers ex 9635,9636, etc. rather than the default 8899. So in my case I am sending commands to 192.168.1.47:9635 for the first group of four then 192.168.1.47:9636 for the second group of four, etc. I was thinking I could specify the port by putting another entry box in the html for the node but have no idea in the js it would use that variable. Hope this makes some kind of sense.
Thanks again for any guidance.
Robert

**Comment by mwittig** [comment]
OK, I see. I have implemented this and will publish a new release soon.

**Comment by orbyog** [comment]
That's great, Thank you so much.
Robert

**Comment by mwittig** [comment]
you're welcome!

published node-red-contrib-milight-2@1.0.8
