### ISSUE TITLE
Zone ALL fehlt

### ISSUE THREAD

**Issue by Matten-Matten** [mwittig/node-red-contrib-milight#7]
Ist es möglich Zone ALL einzufügen?

**Comment by mwittig** [comment]
Hi, probiere es mal mit Zone `0`.

**Comment by mwittig** [comment]
Ich nehme mal, dass die Frage beantwortet ist und schließe das Ticket. Falls Du weitere Anmerkungen hast, kannst Du das Ticket ggf wieder öffnen.

**Comment by Matten-Matten** [comment]
Danke hat geholfen. Vielleicht kannst du das ja in den Dokumentationen festhalten.

Gruß
Matten Matten
